import Head from "next/head";
import Header from "@/components/organisms/Header";
import AboutMe from "@/components/organisms/AboutMe";

export default function About() {
  return (
    <>
      <Head>
        <title>Bala | Portfolio | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AboutMe />
    </>
  );
}
