import Head from "next/head";
import Header from "@/components/organisms/Header";
import Skills from "@/components/organisms/Skills";

export default function skills() {
  return (
    <>
      <Head>
        <title>Bala | Portfolio | Skills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Skills />
    </>
  );
}
